Chetan katkar

23102A0024

In [49]:
# Check that the R kernel is actually running
R.version.string
Sys.getenv("R_HOME")

[1] "R version 4.6.1 (2026-06-24)"

[1] "/usr/lib/R"

## 1. Help for `seq`

`seq(from = 1, to = 1, by = ((to - from)/(length.out - 1)),
     length.out = NULL, along.with = NULL, ...)`

In [50]:
# Documentation for the seq command
help("seq")
# args(seq) is a compact alternative
args(seq)

function (...)
NULL

## 2. Continuous sequences with constant unit increment (integers)

In [51]:
1:10
10:1
5:15
15:5

 [1]  1  2  3  4  5  6  7  8  9 10

 [1] 10  9  8  7  6  5  4  3  2  1

 [1]  5  6  7  8  9 10 11 12 13 14 15

 [1] 15 14 13 12 11 10  9  8  7  6  5

## 3. Unit increment with negative numbers

In [52]:
-1:-10
-10:-1
-5:-15
-15:-5

 [1]  -1  -2  -3  -4  -5  -6  -7  -8  -9 -10

 [1] -10  -9  -8  -7  -6  -5  -4  -3  -2  -1

 [1]  -5  -6  -7  -8  -9 -10 -11 -12 -13 -14 -15

 [1] -15 -14 -13 -12 -11 -10  -9  -8  -7  -6  -5

## 4. Unit increment starting from a decimal number

The increment stays 1; only the starting value carries the decimal part.
The sequence stops before crossing the end value.

In [53]:
1.23:10
1.23:10.54
10.54:2.23

[1] 1.23 2.23 3.23 4.23 5.23 6.23 7.23 8.23 9.23

 [1]  1.23  2.23  3.23  4.23  5.23  6.23  7.23  8.23  9.23 10.23

[1] 10.54  9.54  8.54  7.54  6.54  5.54  4.54  3.54  2.54

In [54]:
-1.23:-10
-5.23:6

[1] -1.23 -2.23 -3.23 -4.23 -5.23 -6.23 -7.23 -8.23 -9.23

 [1] -5.23 -4.23 -3.23 -2.23 -1.23 -0.23  0.77  1.77  2.77  3.77  4.77  5.77

## 5. `seq(10)` is the same as `seq(1:10)`

In [55]:
seq(10)
seq(1:10)

 [1]  1  2  3  4  5  6  7  8  9 10

 [1]  1  2  3  4  5  6  7  8  9 10

## 6. Sequences with a predefined variable and constant increment

In [56]:
x = 2
seq(1, x, x/10)

[1] 1.0 1.2 1.4 1.6 1.8 2.0

In [57]:
x = 50
seq(0, x, x/10)

 [1]  0  5 10 15 20 25 30 35 40 45 50

## 7. The outcome of a sequence can be stored

In [58]:
x = seq(1, 50, 1/2)
x

 [1]  1.0  1.5  2.0  2.5  3.0  3.5  4.0  4.5  5.0  5.5  6.0  6.5  7.0  7.5  8.0
[16]  8.5  9.0  9.5 10.0 10.5 11.0 11.5 12.0 12.5 13.0 13.5 14.0 14.5 15.0 15.5
[31] 16.0 16.5 17.0 17.5 18.0 18.5 19.0 19.5 20.0 20.5 21.0 21.5 22.0 22.5 23.0
[46] 23.5 24.0 24.5 25.0 25.5 26.0 26.5 27.0 27.5 28.0 28.5 29.0 29.5 30.0 30.5
[61] 31.0 31.5 32.0 32.5 33.0 33.5 34.0 34.5 35.0 35.5 36.0 36.5 37.0 37.5 38.0
[76] 38.5 39.0 39.5 40.0 40.5 41.0 41.5 42.0 42.5 43.0 43.5 44.0 44.5 45.0 45.5
[91] 46.0 46.5 47.0 47.5 48.0 48.5 49.0 49.5 50.0

In [59]:
y = 2 * x
y

 [1]   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18  19  20
[20]  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37  38  39
[39]  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57  58
[58]  59  60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
[77]  78  79  80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96
[96]  97  98  99 100

## 8. Index vector: `seq(along = x)`

`seq(along = x)` returns the positions 1, 2, ..., length(x).

In [60]:
x = c(9, 8, 7, 6)
ind = seq(along = x)
ind

[1] 1 2 3 4

In [61]:
# Accessing a value of the vector through the index vector
x[ ind[2] ]

[1] 8

## 9. Current date and time

`Sys.time()` gives the current time and date, `Sys.Date()` gives the current date.

In [62]:
Sys.time()
Sys.Date()

[1] "2026-09-01 08:53:36 UTC"

[1] "2026-09-01"

---
# Lecture 27 — Sequences of Dates and Alphabets

## 10. Sequence of the first day of years

In [63]:
seq(as.Date("2010-01-01"), as.Date("2017-01-01"), by = "years")

[1] "2010-01-01" "2011-01-01" "2012-01-01" "2013-01-01" "2014-01-01"
[6] "2015-01-01" "2016-01-01" "2017-01-01"

## 11. Sequence of days

In [64]:
seq(as.Date("2017-01-01"), by = "days", length = 6)

[1] "2017-01-01" "2017-01-02" "2017-01-03" "2017-01-04" "2017-01-05"
[6] "2017-01-06"

## 12. Sequence of months

In [65]:
seq(as.Date("2017-01-01"), by = "months", length = 6)

[1] "2017-01-01" "2017-02-01" "2017-03-01" "2017-04-01" "2017-05-01"
[6] "2017-06-01"

## 13. Sequence by years

In [66]:
seq(as.Date("2017-01-01"), by = "years", length = 6)

[1] "2017-01-01" "2018-01-01" "2019-01-01" "2020-01-01" "2021-01-01"
[6] "2022-01-01"

## 14. Sequence with a defined start and end date (backwards)

In [67]:
startdate = as.Date("2016-1-1")
enddate   = as.Date("2017-1-1")
out = seq(enddate, startdate, by = "-1 month")
out

 [1] "2017-01-01" "2016-12-01" "2016-11-01" "2016-10-01" "2016-09-01"
 [6] "2016-08-01" "2016-07-01" "2016-06-01" "2016-05-01" "2016-04-01"
[11] "2016-03-01" "2016-02-01" "2016-01-01"

## 15. Sequence of lowercase alphabets: `letters`

In [68]:
letters

 [1] "a" "b" "c" "d" "e" "f" "g" "h" "i" "j" "k" "l" "m" "n" "o" "p" "q" "r" "s"
[20] "t" "u" "v" "w" "x" "y" "z"

## 16. `letters[from_index:to_index]`

In [69]:
letters[1:3]
letters[3:1]
letters[21:23]
letters[2]

[1] "a" "b" "c"

[1] "c" "b" "a"

[1] "u" "v" "w"

[1] "b"

## 17. Sequence of uppercase alphabets: `LETTERS`

In [70]:
LETTERS

 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T" "U" "V" "W" "X" "Y" "Z"

## 18. `LETTERS[from_index:to_index]`

In [71]:
LETTERS[1:3]
LETTERS[3:1]
LETTERS[21:23]
LETTERS[2]

[1] "A" "B" "C"

[1] "C" "B" "A"

[1] "U" "V" "W"

[1] "B"

---
# Lecture 28 — Repeats

## 19. Help for `rep`

- `rep(x)` — replicates the values in x
- `rep(x, times = n)` — repeat x as a whole n times
- `rep(x, each = n)` — repeat each cell n times
- `rep(x, length.out = n)`, `rep(x, length = n)`, `rep_len(x, length.out)`

In [72]:
help("rep")
args(rep)

function (x, ...)
NULL

## 20. Repeat an object n times

In [73]:
rep(3.5, times = 10)
rep(1:4, 2)

 [1] 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5 3.5

[1] 1 2 3 4 1 2 3 4

## 21. `times` versus `each`

In [74]:
x = 1:4
x
rep(x, times = 3)
rep(x, each = 3)

[1] 1 2 3 4

 [1] 1 2 3 4 1 2 3 4 1 2 3 4

 [1] 1 1 1 2 2 2 3 3 3 4 4 4

## 22. Effect of the ordering of `each` and `times`

Both give the same result — R matches the arguments by name, not by position.

In [75]:
rep(1:4, each = 2)
rep(1:4, each = 2, times = 3)
rep(1:4, times = 3, each = 2)

[1] 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

 [1] 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4 1 1 2 2 3 3 4 4

## 23. Every object repeated a different number of times

The `times` argument can itself be a vector of the same length as x.

In [76]:
rep(1:4, 2:5)

 [1] 1 1 2 2 2 3 3 3 3 4 4 4 4 4

In [77]:
ans = seq(from = 2, to = 8, by = 2)
ans
rep(1:4, ans)

[1] 2 4 6 8

 [1] 1 1 2 2 2 2 3 3 3 3 3 3 4 4 4 4 4 4 4 4

## 24. Repeating a matrix

A matrix is stored column-wise, so `rep` flattens it column by column.

In [78]:
x = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = T)
x
rep(x, 3)

     [,1] [,2]
[1,] 1    2
[2,] 3    4

 [1] 1 3 2 4 1 3 2 4 1 3 2 4

## 25. Repetition of characters

In [79]:
rep(c("a", "b", "c"), 2)
rep(c("apple", "banana", "cake"), 2)

[1] "a" "b" "c" "a" "b" "c"

[1] "apple"  "banana" "cake"   "apple"  "banana" "cake"

## 26. Repetition for a pre-specified length

In [80]:
rep(2, length.out = 5)
rep(2, length = 5)
rep(c(2, 3), length = 5)
rep(c(2, 3, 4), length = 5)

[1] 2 2 2 2 2

[1] 2 2 2 2 2

[1] 2 3 2 3 2

[1] 2 3 4 2 3

In [81]:
rep("apple", length = 5)
rep(c("a", "b", "c"), length = 2)
rep(c("a", "b", "c"), length = 5)

[1] "apple" "apple" "apple" "apple" "apple"

[1] "a" "b"

[1] "a" "b" "c" "a" "b"

---
# Lecture 29 — Sorting, Ordering and Mode

## 27. Sorting

`sort(x, decreasing = FALSE, na.last = NA)`

- `na.last = TRUE` — missing values placed last
- `na.last = FALSE` — missing values placed first
- `na.last = NA` — missing values removed

In [82]:
y = c(8, 5, 7, 6)
y
sort(y)
sort(y, decreasing = TRUE)

[1] 8 5 7 6

[1] 5 6 7 8

[1] 8 7 6 5

## 28. Sorting with missing values

In [83]:
ymiss = c(8, NA, 5, 7, NA, 6)
sort(ymiss)                  # na.last = NA, NAs dropped
sort(ymiss, na.last = TRUE)  # NAs pushed to the end
sort(ymiss, na.last = FALSE) # NAs pulled to the front

[1] 5 6 7 8

[1]  5  6  7  8 NA NA

[1] NA NA  5  6  7  8

## 29. Ordering

`order` returns the **positions** that would sort the vector.

| Value | 9 | 8 | 5 | 7 | 6 |
|---|---|---|---|---|---|
| Position | 1 | 2 | 3 | 4 | 5 |

| Ordered value | 5 | 6 | 7 | 8 | 9 |
|---|---|---|---|---|---|
| Position | 3 | 5 | 4 | 2 | 1 |

In [84]:
y = c(9, 8, 5, 7, 6)
y
order(y)
order(y, decreasing = TRUE)

[1] 9 8 5 7 6

[1] 3 5 4 2 1

[1] 1 2 4 5 3

In [85]:
# order() used to actually rearrange the vector
y[order(y)]

[1] 5 6 7 8 9

## 30. Mode

Every object has a mode, which indicates how the object is stored in memory.

In [86]:
mode(2.432)
mode(c(3, 4, 5, 6, 7, 8))
mode("India")
mode(c("India", "CANADA"))

[1] "numeric"

[1] "numeric"

[1] "character"

[1] "character"

In [87]:
mode(factor(c("MP", "UP")))
mode(list("India", "CANADA"))
mode(data.frame(x = 1:2, y = c("India", "CANADA")))
mode(print)

[1] "numeric"

[1] "list"

[1] "list"

[1] "function"

---
# Lecture 30 — Lists

## 31. Vectors and matrices hold only one type of data

A list, in contrast, can contain elements of different modes, can hold structured
objects such as data frames, can be indexed by position (`x[[5]]`), can be
sub-setted (`x[c(2,5)]`), and its elements can be named
(`x[["Students"]]` or `x$Students`).

In [88]:
x1 = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = T)
x2 = matrix(nrow = 2, ncol = 2, data = 5:8, byrow = T)
x1
x2
x1 + x2

     [,1] [,2]
[1,] 1    2
[2,] 3    4

     [,1] [,2]
[1,] 5    6
[2,] 7    8

     [,1] [,2]
[1,]  6    8
[2,] 10   12

## 32. A matrix cannot mix modes

Assigning a character into a numeric matrix coerces the whole matrix to character,
and arithmetic then fails.

`try()` is used here only so that the error message is printed without stopping
the notebook.

In [89]:
x1[2, 1] = "hello"
x1
try(x1 + x2)

     [,1]  [,2]
[1,] 1     2
[2,] hello 4

Error in x1 + x2 : non-numeric argument to binary operator

## 33. Lists can contain any kind of object, including matrices

In [90]:
x1 = matrix(nrow = 2, ncol = 2, data = 1:4, byrow = T)
x2 = matrix(nrow = 2, ncol = 2, data = 5:8, byrow = T)
matlist = list(x1, x2)
matlist

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[2]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

## 34. `[ ]` returns a sublist, `[[ ]]` returns the element itself

In [91]:
matlist[1]
matlist[2]

[[1]]
     [,1] [,2]
[1,]    1    2
[2,]    3    4

[[1]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

In [92]:
# Compare with the double bracket
matlist[[1]]
mode(matlist[1])    # still a list
mode(matlist[[1]])  # the matrix itself

     [,1] [,2]
[1,] 1    2
[2,] 3    4

[1] "list"

[1] "numeric"

## 35. A list containing different object types

In [93]:
z1 = list( c("water", "juice", "lemonade"),
           rep(1:4, each = 2),
           matrix(data = 5:8, nrow = 2, ncol = 2, byrow = T) )
z1

[[1]]
[1] "water"    "juice"    "lemonade"

[[2]]
[1] 1 1 2 2 3 3 4 4

[[3]]
     [,1] [,2]
[1,]    5    6
[2,]    7    8

## 36. Accessing elements of a list

`z1[1][2]` returns NULL, while `z1[[1]][2]` returns the desired element.

In [94]:
z1[[1]]
z1[1][2]     # NULL - wrong bracket
z1[[1]][2]   # "juice" - correct

[1] "water"    "juice"    "lemonade"

[[1]]
NULL

[1] "juice"

## 37. Named list elements

`x[["Students"]]` and `x$Students` refer to the same element.

In [95]:
x = list(Students = c("Amit", "Rekha", "Swaroop"),
         Marks = c(88, 91, 79),
         Course = "R Programming")
x
x[["Students"]]
x$Students

$Students
[1] "Amit"    "Rekha"   "Swaroop"

$Marks
[1] 88 91 79

$Course
[1] "R Programming"

[1] "Amit"    "Rekha"   "Swaroop"

[1] "Amit"    "Rekha"   "Swaroop"

In [96]:
# Sublist of selected elements
x[c(1, 3)]
names(x)
length(x)

$Students
[1] "Amit"    "Rekha"   "Swaroop"

$Course
[1] "R Programming"

[1] "Students" "Marks"    "Course"

[1] 3

---
## Quick recap

| Task | Command |
|---|---|
| Unit-increment sequence | `1:10`, `-5:-15` |
| General sequence | `seq(from, to, by, length.out)` |
| Index vector | `seq(along = x)` |
| Current date / time | `Sys.Date()`, `Sys.time()` |
| Date sequence | `seq(as.Date(...), by = "months", length = 6)` |
| Alphabets | `letters`, `LETTERS` |
| Repeat whole object | `rep(x, times = n)` |
| Repeat each element | `rep(x, each = n)` |
| Repeat to a fixed length | `rep(x, length.out = n)` |
| Sort values | `sort(x, decreasing, na.last)` |
| Sort positions | `order(x)` |
| Storage type | `mode(x)` |
| Mixed-type container | `list(...)`, `x[[i]]`, `x$name` |